version: '3.4'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: redis
    networks:
      - main
    ports:
      - "6379:6379"
    restart: on-failure

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - main
    ports:
      - "5433:5432"
    restart: on-failure
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "wait-for postgres:5432 && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn mysite.wsgi -b 0.0.0.0:8000"
    container_name: app
    depends_on:
      - postgres
      - redis
    expose:
      - "8000"
    hostname: app
    image: app-image
    networks:
      - main
    restart: on-failure

  celery_worker:
    command: sh -c "wait-for redis:6379 && wait-for app:8000 -- celery -A mysite worker -l info"
    container_name: celery_worker
    depends_on:
      - postgres
      - redis
    hostname: celery_worker
    image: app-image
    networks:
      - main
    restart: on-failure

  celery_flower:
    command: sh -c "wait-for redis:6379 && wait-for app:8000 -- celery -A mysite flower worker -l info"
    container_name: celery_flower
    depends_on:
      - postgres
      - redis
    hostname: celery_worker
    image: app-image
    ports:
    - "5555:5555"
    networks:
      - main
    restart: on-failure

  celery_beat:
    command: sh -c "wait-for redis:6379 && wait-for app:8000 -- celery -A mysite beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    container_name: celery_beat
    depends_on:
      - app
      - postgres
      - redis
    hostname: celery_beat
    image: app-image
    networks:
      - main
    restart: on-failure

networks:
  main:

volumes:
  postgresql-data:
